export enum UserAccountStatusEnum {
  INIT = 'INIT',
  ACTIVE = 'ACTIVE',
  BAN = 'BAN',
  PARMANENT_BAN = 'PARMANENT_BAN',
  DEACTIVATED = 'DEACTIVATED',
  PARMANENT_DEACTIVATED = 'PARMANENT_DEACTIVATED',
}
